### ISSUE TITLE
assignment count mismatch

### ISSUE THREAD

**Issue by tmaiaroto** [rsc/grind#2]
I'm getting `../../../rsc.io/grind/vardecl/vardecl.go:84: assignment count mismatch: 2 = 3` when I go get the package. I looked into NodeEval() and it seemed correct. So I'm at a loss for more suggestions, sorry.

I'm using go version 1.4 (darwin/amd64) in case it matters.

**Comment by omeid** [comment]
You most probably have an old [x/tools/go/types](golang.org/x/tools/go/types), updating that should get you going.

**Comment by rsc** [comment]
Yes, you probably have an old go/types. Use go get -u rsc.io/grind.

**Comment by tmaiaroto** [comment]
doh! thanks

**Comment by dmitshur** [comment]
> Use go get -u rsc.io/grind.

Why does the [README](https://github.com/rsc/grind/blob/master/README.md) suggest not using `-u` by default?

**Comment by tmaiaroto** [comment]
Hmm well looks like I have a bigger issue to solve. I have all the old p/tools and now have to figure out how to get the new/moved ones apparently.

**Comment by dmitshur** [comment]
Remove them (you don't have unsaved work in those repos, do you?) and go get -u everything again. It's the simplest way.
